### ISSUE TITLE
d3 v3 -> v4 coding 변경 적용

### ISSUE THREAD

**Issue by TovenBae** [TovenBae/eyelink-parstream#1]
현재 테스트 모듈 d3 v3을  v4 coding 변경 적용

**Comment by ohliAnnie** [comment]
- dc.js 는 d3.js v3.x 기반으로 개발되었습니다.
- d3.js v4가 올해 적용되어 아직 예제들이 많이 나와있지 않습니다.

위 상황을 고려하여 현 상황에서는 v3를 사용하는 것이 좋다고 판단됩니다.
v4에 관한 정보들을 꾸준히 확인하여
빠른 시일 내에 적용 할 수 있도록 하겠습니다.

**Comment by TovenBae** [comment]
OK
