### ISSUE TITLE
DB insert 시 중복 저장

### ISSUE THREAD

**Issue by ohliAnnie** [TovenBae/eyelink-parstream#103]
user 혹은 cluster insert시 동일 data 중복 저장 문제

**Comment by TovenBae** [comment]
- 발생원인
아마도 partition으로 정의된 colunm 의 index가 range index로 정의되어 발생하는 현상으로 추정됨

- 해결방법
테이블에 data_year 필드를 한 추가하고 index equal로 정의한다.

> CREATE TABLE tb_user_info
> (
>      data_year INT16          INDEX EQUAL CSV_COLUMN 0,
>   user_id VARSTRING(20) COMPRESSION NONE MAPPING_FILE_GRANULARITY 256 ,
>   user_name VARSTRING(20) COMPRESSION NONE MAPPING_FILE_GRANULARITY 256 ,
>   user_pw VARSTRING(20) COMPRESSION NONE MAPPING_FILE_GRANULARITY 256 ,
>   user_role VARSTRING(15) COMPRESSION NONE MAPPING_FILE_GRANULARITY 256 ,
>   user_email VARSTRING(50) COMPRESSION NONE MAPPING_FILE_GRANULARITY 256,
>   reg_date  TIMESTAMP  INDEX RANGE INDEX_GRANULARITY DAY,
> )
> PARTITION BY data_year
> DISTRIBUTE OVER data_year
> ORDER BY data_year
> IMPORT_DIRECTORY_PATTERN '.*'
> IMPORT_FILE_PATTERN 'tb_user_info.*\.csv'
> ETL (select *  from csvfetch(tb_user_info));
