### ISSUE TITLE
Analysis/clustering 보완사항

### ISSUE THREAD

**Issue by eddkkang** [TovenBae/eyelink-parstream#123]
1. clustering chart에서 ampere 팩터에 대한 y축값의 범위 변경 (기존 0~240 -> 0.0 ~ 1.0)
2. History에서 3hour, 6hour에 대한 interval에 대한 값 표시 (기존 180mins -> 3hours)

**Comment by ohliAnnie** [comment]
1. 수정 완료
2. 수정 완료
