### ISSUE TITLE
GroupBar Tooltip

### ISSUE THREAD

**Issue by ohliAnnie** [TovenBae/eyelink-parstream#50]
http://bl.ocks.org/juan-cb/ac731adaeadd3e855d26

nvd3를 라이브러리라서 설치하고 해야할 것이 많네요 ㅠㅠ
얘는 간결하긴 한데 이건 어떠신가요?

**Comment by TovenBae** [comment]
일단 위의걸로 진행하고 추후 검토해서 진행 여부 결정 해요

**Comment by ohliAnnie** [comment]
네~ 우선 다음차트 먼저 진행중이여서 마무리 하고 그룹바 툴팁 진행하겠습니다

**Comment by ohliAnnie** [comment]
구현 완료 하였습니다. (http://localhost:5223/reports/d3 - 6번째)

**Comment by TovenBae** [comment]
OK
